<script>
import APIsBox from "./APIsBox.vue";
import TailDown from "@/assets/taildown.js";
import SidebarNavs from "./SidebarNavs.vue";
import ColorThemeBox from "./ColorThemeBox.vue";
import ScriptsDisplay from "./ScriptsDisplay.vue";
import DashboardStats from "./DashboardStats.vue";
import HeaderSearchbox from "./HeaderSearchbox.vue";

export default {
  name: "APIsDashboardComponent",
  components: {
    APIsBox,
    SidebarNavs,
    ColorThemeBox,
    ScriptsDisplay,
    DashboardStats,
    HeaderSearchbox,
  },
  data() {
    return {
      TailDown: TailDown,
      documentation: String,
      color: localStorage.color,
    };
  },
  mounted() {
    const Markdown = new this.TailDown({
      a: {
        customClass: `text-${localStorage.color}`,
      },
      p: {
        customClass: "text-gray-300",
      },
      h1: {
        customClass: "text-gray-300",
      },
    });

    this.documentation = Markdown.parse(`
## **BloxSafe**
Welcome to the [documentation](/docs), here you will learn to use the panel.



### **Dashboard**
<small>On the dashboard page you can view your stats and scripts. To edit a script click on the "manage" button, this will
take you to the script edit page, from their you can change the code, change name, get link and configure script
settings.</small>



### **APIs**
<small>You can use the APIs to manage your data programatically. You can generate API keys from the APIs page.</small>



### **Tools**
<small>BloxSafe offers tools like [Obfuscator](/tools/obfuscator), [Script Hub](/tools/hub), [Discord Webhook](/tools/webhook) and more. The obfuscation tool is to make your code unreadable to prevent stealing. The script hub tool creates a roblox script hub with your scripts, the script hub code is auto generated by BloxSafe. You can also connect your discord wehbook to receive important information.</small>



### **Script Hub**
<small>BloxSafe automatically creates a script hub for every user. Basically a pre-written code that, once injected in a Roblox game shows a script hub GUI with your best-rated scripts</small>
`);
  },
};
</script>
<template>
  <div class="w-full">
    <div
      class="hidden md:flex md:w-64 md:flex-col md:fixed md:inset-y-0 border border-bray-300"
    >
      <div class="flex-1 flex flex-col min-h-0 bg-bray-500">
        <div class="flex items-center h-16 flex-shrink-0 px-4 bg-bray-500">
          <h1 class="text-2xl font-bold text-gray-300">
            <span :class="`text-${color}`" class="">Blox</span><span>Safe</span>
          </h1>
        </div>
        <div class="flex-1 flex flex-col overflow-y-auto">
          <nav class="flex-1 px-3 py-4 space-y-1">
            <SidebarNavs />
          </nav>
          <ColorThemeBox />
        </div>
      </div>
    </div>
    <div class="md:pl-64 flex flex-col">
      <div
        class="sticky top-0 z-10 border-bray-300 border-b flex-shrink-0 flex h-16 bg-bray-500"
      >
        <button
          type="button"
          class="px-4 border-r border-bray-300 text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500 md:hidden"
        >
          <span class="sr-only">Open sidebar</span>

          <svg
            class="h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h7"
            />
          </svg>
        </button>
        <div class="flex-1 px-5 flex justify-between">
          <div class="flex-1 flex">
            <HeaderSearchbox />
          </div>
        </div>
      </div>
      <div id="docs" class="text-gray-300 p-4" v-html="documentation"></div>

      <!-- Content-->
    </div>
  </div>
</template>
